spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=WorkoutBuddyDB;encrypt=false
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  # JdbcTemplate設定
  jdbc:
    template:
      query-timeout: 30
      max-rows: 1000
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    check-template-location: false
  
  security:
    user:
      name: admin
      password: admin

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.benesse.workoutbuddy: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# アプリケーション固有の設定
app:
  workout:
    max-duration-minutes: 300
    min-duration-minutes: 1
  buddy:
    max-buddies-per-user: 10
  notification:
    max-message-length: 500 